import { Activity, Menu, X } from "lucide-react";
import { useState } from "react";
import { Link, NavLink } from "react-router-dom";
import { navItems } from "../routes/navItems";
export default function Navbar() {
  const [open,setOpen]=useState(false);
  const linkClass=({isActive}:{isActive:boolean})=>`rounded-full px-4 py-2 text-sm font-medium transition ${isActive?"bg-viva-green text-viva-bg":"text-white/70 hover:bg-white/10 hover:text-white"}`;
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-viva-bg/75 backdrop-blur-2xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-6"><Link to="/" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-viva-green to-viva-cyan text-viva-bg shadow-glow"><Activity size={23}/></span><div><p className="text-xl font-black tracking-tight">VivaTrack</p><p className="-mt-1 text-[11px] uppercase tracking-[0.28em] text-viva-green/70">Fitness SaaS</p></div></Link><nav className="hidden items-center gap-1 xl:flex">{navItems.map(i=><NavLink key={i.path} to={i.path} className={linkClass}>{i.label}</NavLink>)}</nav><div className="hidden items-center gap-3 xl:flex"><Link to="/dashboard" className="rounded-full border border-white/10 bg-white/5 px-5 py-2.5 text-sm font-semibold text-white/80 hover:bg-white/10">View Demo</Link><Link to="/pricing" className="rounded-full bg-viva-green px-5 py-2.5 text-sm font-black text-viva-bg">Start Free</Link></div><button onClick={()=>setOpen(!open)} className="rounded-xl border border-white/10 bg-white/5 p-2 xl:hidden" aria-label="Open menu">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-white/10 bg-viva-bg/95 px-4 pb-5 xl:hidden"><nav className="grid gap-2 pt-4">{navItems.map(i=><NavLink key={i.path} to={i.path} className={linkClass} onClick={()=>setOpen(false)}>{i.label}</NavLink>)}<Link to="/pricing" onClick={()=>setOpen(false)} className="mt-2 rounded-full bg-viva-green px-5 py-3 text-center text-sm font-black text-viva-bg">Start Free</Link></nav></div>}</header>;
}
